# Generated by Django 5.1.4 on 2024-12-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="film",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="film",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="film",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="film",
            name="film_type",
            field=models.CharField(default="35mm", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="film",
            name="iso",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="film",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="film_covers/"),
        ),
    ]
