# Generated by Django 5.1.4 on 2024-12-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_rename_title_film_name_remove_film_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="cover_image",
            field=models.ImageField(
                default="media/film_covers/testcover5.png", upload_to="film_covers/"
            ),
            preserve_default=False,
        ),
    ]
