# Generated by Django 5.1.4 on 2024-12-12 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_alter_film_cover_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="film",
            old_name="name",
            new_name="film_name",
        ),
    ]
