# Generated by Django 5.1.4 on 2024-12-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0004_rename_name_film_film_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("preferred_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("death_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="artist_covers/"
                    ),
                ),
            ],
        ),
    ]
