# Generated by Django 5.1.4 on 2024-12-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0005_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
