# Generated by Django 5.1.4 on 2024-12-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0007_alter_artist_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
