# Generated by Django 5.1.4 on 2024-12-16 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0008_alter_artist_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="artist_covers/"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Others", "Others")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="preferred_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="RollScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(blank=True, null=True)),
                ("develop_date", models.DateField(blank=True, null=True)),
                ("scan_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "film_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warehouse.film"
                    ),
                ),
            ],
        ),
    ]
