# Generated by Django 5.1.4 on 2024-12-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0009_alter_artist_cover_image_alter_artist_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollscan",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
