# Generated by Django 5.1.4 on 2024-12-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0010_rollscan_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllMedia",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("media_type", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("media_src", models.CharField(max_length=255)),
                (
                    "media_src_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
