# Generated by Django 5.1.4 on 2024-12-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0011_allmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allmedia",
            name="media_src",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
