# Generated by Django 5.1.4 on 2024-12-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0012_alter_allmedia_media_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allmedia",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.artist",
            ),
        ),
    ]
