# Generated by Django 5.1.4 on 2024-12-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0013_alter_allmedia_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="allmedia",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
