# Generated by Django 5.1.4 on 2025-02-05 04:31

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0014_allmedia_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollscan",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="rollscan",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rollscan",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
